### PR TITLE
 Added link to detection output in Stata console

### PR DESCRIPTION
**Pull request by luisesanmartin**
Solves #25

### CODE REVIEW

**Comment by luisesanmartin** [comment]
@luizaandrade this is ready for review too. You can download the code from this branch with `net install stata_linter, from("https://raw.githubusercontent.com/worldbank/stata-linter/develop-add-links-to-detection") replace` and then use it in your computer as the readme file explains

**Comment by luisesanmartin** [comment]
Note that the links are only in the detection output, which is generated with the `excel()` option. I haven't added links in the "correction" outputs but it would be straightforward to do if we wanted to include it

**Comment by RRMaximiliano** [comment]
This is the output I'm getting when exporting the new do file: 

image

**Comment by RRMaximiliano** [comment]
All excel related options gave me error: 

image

**Comment by luizaandrade** [comment]
I have fixed the bugs reported by Rony on the 3 previous commits

**Pull request merged**
