### PR TITLE
Removed nocheck option

### PR DESCRIPTION
**Pull request by luisesanmartin**
Solves #24

### CODE REVIEW

**Comment by luisesanmartin** [comment]
@luizaandrade this is ready for review. You can install this version with `net install stata_linter, from("https://raw.githubusercontent.com/worldbank/stata-linter/develop-remove-nocheck") replace` and then use it as explained in the initial readme file

**Comment by RRMaximiliano** [comment]
I'm getting this error when trying to to output to excel: 

image

**Comment by RRMaximiliano** [comment]
Finally, when we test for multiple files in the same directory, we get twice the output table. All the other options are running well.

**Comment by luisesanmartin** [comment]
> I'm getting this error when trying to to output to excel:
> 
> image
> 
> I had to delete the excel file and re-run the command. Also, the excel file keeps the checks, would that be what we want there?

Thanks, @RRMaximiliano . I'm unable to replicate the error. I tried `lint "test/bad.do", nosummary excel(detect_link.xlsx)` twice, even when the output file already exists, and it works. Can I ask if you're certain to be using the code from this branch?

**Comment by luisesanmartin** [comment]
> I had to delete the excel file and re-run the command. Also, the excel file keeps the checks, would that be what we want there?

@RRMaximiliano also, what do you mean with "the excel file keeps the checks"? is it that the excel file is supposed to list only "style" and not "check" issues?

**Comment by luisesanmartin** [comment]
> Finally, when we test for multiple files in the same directory, we get twice the output table. All the other options are running well.

@RRMaximiliano I'm also unable to replicate this error. I tried `lint "test", nosummary excel(detect_link.xlsx)` and the output looks fine. The row tables are not duplicated and the output file is listed only once. Do you remember what was the code you used when you got the error?

**Comment by luizaandrade** [comment]
I am also getting an error:

image

**Comment by luizaandrade** [comment]
I believe this error is coming from not running the updated Python file. I will try merging Luise's changes to master and then reinstalling using net install. I have documented the issue in #30

**Pull request merged**
